#!/bin/bash
echo "Regenerating smlouva13..."
python3 "anon7.2 - s padama.py" smlouva13.docx 2>&1 | grep "Nalezeno osob:"
echo "Regenerating smlouva14..."
python3 "anon7.2 - s padama.py" smlouva14.docx 2>&1 | grep "Nalezeno osob:"
echo "Regenerating smlouva15..."
python3 "anon7.2 - s padama.py" smlouva15.docx 2>&1 | grep "Nalezeno osob:"
echo "Regenerating smlouva16..."
python3 "anon7.2 - s padama.py" smlouva16.docx 2>&1 | grep "Nalezeno osob:"
echo "Regenerating smlouva17..."
python3 "anon7.2 - s padama.py" smlouva17.docx 2>&1 | grep "Nalezeno osob:"
echo "Regenerating smlouva18..."
python3 "anon7.2 - s padama.py" smlouva18.docx 2>&1 | grep "Nalezeno osob:"
echo "Regenerating smlouva19..."
python3 "anon7.2 - s padama.py" smlouva19.docx 2>&1 | grep "Nalezeno osob:"
echo "Regenerating smlouva20..."
python3 "anon7.2 - s padama.py" smlouva20.docx 2>&1 | grep "Nalezeno osob:"
echo "Regenerating smlouva21..."
python3 "anon7.2 - s padama.py" smlouva21.docx 2>&1 | grep "Nalezeno osob:"
echo "Regenerating smlouva22..."
python3 "anon7.2 - s padama.py" smlouva22.docx 2>&1 | grep "Nalezeno osob:"
echo "Regenerating smlouva23..."
python3 "anon7.2 - s padama.py" smlouva23.docx 2>&1 | grep "Nalezeno osob:"
echo "Regenerating smlouva24..."
python3 "anon7.2 - s padama.py" smlouva24.docx 2>&1 | grep "Nalezeno osob:"
echo "Done!"
